export default Promise.resolve([
  {
    avatar: 'https://cdn.vuetifyjs.com/images/lists/1.jpg',
    title: 'Brunch this weekend?',
    to: 'Ali Connors',
    subtitle: `I'll be in your neighborhood doing errands this weekend. Do you want to hang out?`,
    country: 'Russia',
    address: 'Volgogradskaya oblast, Volzhskiy, Mira Ul., bld. 62, appt. 102',
    score: '< 10',
  },
  {
    avatar: 'https://cdn.vuetifyjs.com/images/lists/2.jpg',
    title: 'Summer BBQ <span class="grey--text text--lighten-1">4</span>',
    to: 'to Alex, Scott, Jennifer',
    subtitle: `Wish I could come, but I'm out of town this weekend.`,
    country: 'USA',
    address: '101 Independence Avenue, S.E. Washington, D.C. 20559-6000',
    score: '< 10',
  },
  {
    avatar: 'https://cdn.vuetifyjs.com/images/lists/3.jpg',
    title: 'Oui oui',
    to: 'Sandra Adams',
    subtitle: 'Do you have Paris recommendations? Have you ever been?',
    country: 'Germany',
    address: 'Viersen Rahser, Nordrhein-Westfalen(NW), 41747 02162 13 77 96',
    score: '> 20',
  },
  {
    avatar: 'https://cdn.vuetifyjs.com/images/lists/4.jpg',
    title: 'Birthday gift',
    to: 'Trevor Hansen',
    subtitle: 'Have any ideas about what we should get Heidi for her birthday?',
    country: 'Ukraine',
    address: 'Odesskaya oblast, Odessa, Seminarskaya Ul., bld. 5/А, appt. 27',
    score: '> 20',
  },
  {
    avatar: 'https://cdn.vuetifyjs.com/images/lists/5.jpg',
    title: 'Recipe to try',
    to: 'Britta Holt',
    subtitle: 'We should eat this: Grate, Squash, Corn, and tomatillo Tacos.',
    country: 'Germany',
    address: 'Rüthen, Nordrhein-Westfalen(NW), 59602 02902 34 13 58',
    score: '> 20',
  },
]);
